name: Run Tests

on:
    pull_request:

jobs:
    install-and-build:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: npm-${{ hashFiles('package-lock.json') }}
                  restore-keys: npm-
            - run: npm ci
            - run: npm run build --production

    test:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: npm-${{ hashFiles('package-lock.json') }}
                  restore-keys: npm-
            - run: npm ci
            - run: npm run test
